

class AM:
    def __init__(self):
        self.cities = [
      "Manaus",
      "Parintins",
      "Itacoatiara",
      "Manacapuru",
      "Coari",
      "Tefé",
      "Tabatinga",
      "Humaitá",
      "Maués",
      "Borba",
      "Autazes",
      "São Gabriel da Cachoeira",
      "Eirunepé",
      "Barcelos",
      "Benjamin Constant",
      "Boca do Acre",
      "Careiro",
      "Iranduba",
      "Santo Antônio do Içá",
      "São Paulo de Olivença",
      "Tabatinga",
      "Rio Preto da Eva",
      "Manicoré",
      "Presidente Figueiredo",
      "Novo Aripuanã",
      "Jutaí",
      "Tonantins",
      "Fonte Boa",
      "Lábrea",
      "Nova Olinda do Norte",
      "Beruri",
      "Uarini",
      "Anamã",
      "Urucurituba",
      "Novo Airão",
      "Silves",
      "Tapauá",
      "Careiro da Várzea",
      "Urucará",
      "Codajás",
      "Atalaia do Norte",
      "Pauini",
      "Itapiranga",
      "Amaturá",
      "Alvarães",
      "Manaquiri",
      "Santa Isabel do Rio Negro",
      "Canutama",
      "Tefé",
      "Japurá",
      "Apui",
      "Carauari",
      "Barreirinha",
      "Novo Airão",
      "Envira",
      "Juruá",
      "Juruá",
      "Itamarati",
      "Uarini",
      "Eirunepé",
      "Fonte Boa",
      "Guajará",
      "Humaitá",
      "Ipixuna",
      "Iranduba",
      "Itapiranga",
      "Japurá",
      "Juruá",
      "Jutaí",
      "Lábrea",
      "Manacapuru",
      "Manaquiri",
      "Manaus",
      "Manicoré",
      "Maraã",
      "Maués",
      "Nhamundá",
      "Nova Olinda do Norte",
      "Novo Airão",
      "Novo Aripuanã",
      "Parintins",
      "Pauini",
      "Presidente Figueiredo",
      "Rio Preto da Eva",
      "Santa Isabel do Rio Negro",
      "Santo Antônio do Içá",
      "São Gabriel da Cachoeira",
      "São Paulo de Olivença",
      "São Sebastião do Uatumã",
      "Silves",
      "Tabatinga",
      "Tapauá",
      "Tefé",
      "Tonantins",
      "Uarini",
      "Urucará",
      "Urucurituba"
    ]