

class BA:
    def __init__(self):
        self.cities = [
      "Salvador",
      "Feira de Santana",
      "Vitória da Conquista",
      "Camaçari",
      "Itabuna",
      "Juazeiro",
      "Lauro de Freitas",
      "Ilhéus",
      "Jequié",
      "Teixeira de Freitas",
      "Barreiras",
      "Porto Seguro",
      "Simões Filho",
      "Paulo Afonso",
      "Eunápolis",
      "Santo Antônio de Jesus",
      "Valença",
      "Candeias",
      "Luís Eduardo Magalhães",
      "Guanambi",
      "Jacobina",
      "Itapetinga",
      "Serrinha",
      "Senhor do Bonfim",
      "Dias d'Ávila",
      "Irecê",
      "Campo Formoso",
      "Conceição do Coité",
      "Itaberaba",
      "Brumado",
      "Ipirá",
      "Ibotirama",
      "Euclides da Cunha",
      "Mata de São João",
      "Ubaitaba",
      "Iguaí",
      "Cachoeira",
      "Amargosa",
      "Alagoinhas",
      "Santa Maria da Vitória",
      "Jaguarari",
      "Irará",
      "Barra",
      "Mucuri",
      "Caetité",
      "Itamaraju",
      "Itapicuru",
      "Xique-Xique",
      "Macajuba",
      "Ribeira do Piauí",
      "Camamu",
      "São Desidério",
      "Inhambupe",
      "Itaberaba",
      "Conde",
      "Santa Rita de Cássia",
      "Miguel Calmon",
      "Abaré",
      "Iramaia",
      "Bom Jesus da Lapa",
      "Correntina",
      "Itanhém",
      "Andaraí",
      "Jitaúna",
      "Barrocas",
      "Wagner",
      "Itacaré",
      "Jaborandi",
      "Nova Soure",
      "Umburanas",
      "Gentio do Ouro",
      "Biritinga",
      "Canudos",
      "Sapeaçu",
      "Lapão",
      "Buritirama",
      "Itaparica",
      "Mucugê",
      "Santa Inês",
      "Sento Sé",
      "Cícero Dantas",
      "Candeal",
      "Itagi",
      "Crisópolis",
      "Belmonte",
      "Canavieiras",
      "São Gonçalo dos Campos",
      "Paramirim"
    ]