

class CE:
    def __init__(self):
        self.cities = [
        "Fortaleza",
        "Caucaia",
        "Juazeiro do Norte",
        "Maracanaú",
        "Sobral",
        "Crato",
        "Itapipoca",
        "Maranguape",
        "Iguatu",
        "Quixadá",
        "Pacajus",
        "Quixeramobim",
        "Crateús",
        "Aquiraz",
        "Canindé",
        "Russas",
        "Tianguá",
        "Eusébio",
        "Cascavel",
        "Icó",
        "Pacatuba",
        "Aracati",
        "Acaraú",
        "Ipu",
        "Morada Nova",
        "Limoeiro do Norte",
        "Camocim",
        "Boa Viagem",
        "Tauá",
        "Guaraciaba do Norte",
        "Varjota",
        "Campos Sales",
        "Jaguaribe",
        "Ubajara",
        "Ararendá",
        "São Benedito",
        "Massapê",
        "Nova Russas",
        "Parambu",
        "Croatá",
        "Amontada",
        "Itarema",
        "Irauçuba",
        "Jaguaruana",
        "Canindé",
        "Pentecoste",
        "Pindoretama",
        "Santa Quitéria",
        "Acopiara",
        "Aquiraz",
        "Baturité",
        "Beberibe",
        "Brejo Santo",
        "Cascavel",
        "Caucaia",
        "Cedro",
        "Coreaú",
        "Crateús",
        "Crato",
        "Guaiúba",
        "Horizonte",
        "Iguatu",
        "Itaitinga",
        "Jaguaribe",
        "Juazeiro do Norte",
        "Maracanaú",
        "Maranguape",
        "Massapê",
        "Mauriti",
        "Mombaça",
        "Morada Nova",
        "Nova Russas",
        "Pacajus",
        "Pacatuba",
        "Quixadá",
        "Quixeramobim",
        "Redenção",
        "Russas",
        "Santa Quitéria",
        "São Benedito",
        "Sobral",
        "Tabuleiro do Norte",
        "Tauá",
        "Tianguá",
        "Trairi",
        "Ubajara",
        "Varjota",
        "Várzea Alegre",
        "Viçosa do Ceará",
        "Barbalha",
        "Icó",
        "Crato",
        "Itapajé",
        "Solonópole",
        "Catarina",
        "Jucás",
        "Forquilha"
    ]