

class ES:
    def __init__(self):
        self.cities =  [
      "Vitória",
      "Vila Velha",
      "Cariacica",
      "Serra",
      "Linhares",
      "Colatina",
      "Guarapari",
      "Viana",
      "Nova Venécia",
      "Aracruz",
      "Cachoeiro de Itapemirim",
      "Castelo",
      "São Mateus",
      "Ibiraçu",
      "Anchieta",
      "Guaçuí",
      "Baixo Guandu",
      "Marataízes",
      "Afonso Cláudio",
      "Alegre",
      "Domingos Martins",
      "Jaguaré",
      "Santa Teresa",
      "Ponto Belo",
      "Água Doce do Norte",
      "Mimoso do Sul",
      "Muniz Freire",
      "Itapemirim",
      "Piúma",
      "Conceição da Barra",
      "Fundão",
      "Iúna",
      "Vargem Alta",
      "Marechal Floriano",
      "Pancas",
      "Pinheiros",
      "Iconha",
      "Rio Novo do Sul",
      "Santa Leopoldina",
      "Ibatiba",
      "Ibitirama",
      "Ecoporanga",
      "Barra de São Francisco",
      "Mantenópolis",
      "Águia Branca",
      "Montanha",
      "Boa Esperança",
      "Divino de São Lourenço",
      "Laranja da Terra",
      "São Roque do Canaã",
      "Governador Lindenberg",
      "Atílio Vivácqua",
      "Ponto Belo",
      "Pedro Canário",
      "Itaguaçu",
      "Vila Valério",
      "Laranja da Terra",
      "São Roque do Canaã",
      "Conceição do Castelo",
      "São Gabriel da Palha",
      "Mucurici",
      "Santa Maria de Jetibá",
      "Alfredo Chaves",
      "Brejetuba",
      "Santa Maria de Jetibá",
      "Venda Nova do Imigrante",
      "Itarana",
      "Muniz Freire",
      "Domingos Martins",
      "Santa Leopoldina",
      "Conceição da Barra",
      "Montanha",
      "Água Doce do Norte",
      "São José do Calçado",
      "Iúna",
      "Mimoso do Sul",
      "São Gabriel da Palha",
      "Nova Venécia",
      "Ecoporanga",
      "Águia Branca",
      "Governador Lindenberg",
      "Atílio Vivácqua",
      "Barra de São Francisco",
      "Vila Pavão",
      "Vila Valério",
      "Montanha",
      "São Roque do Canaã",
      "Conceição do Castelo",
      "Muniz Freire",
      "Santa Maria de Jetibá",
      "Brejetuba"
    ]