

class MS:
    def __init__(self):
        self.cities = [
      "Campo Grande",
      "Dourados",
      "Três Lagoas",
      "Corumbá",
      "Ponta Porã",
      "Naviraí",
      "Nova Andradina",
      "Aquidauana",
      "Sidrolândia",
      "Paranaíba",
      "Amambai",
      "Maracaju",
      "Rio Brilhante",
      "Coxim",
      "Caarapó",
      "Miranda",
      "Jardim",
      "Bonito",
      "Aparecida do Taboado",
      "Chapadão do Sul",
      "Coronel Sapucaia",
      "Fátima do Sul",
      "Bela Vista",
      "Costa Rica",
      "Terenos",
      "São Gabriel do Oeste",
      "Cassilândia",
      "Ivinhema",
      "Bataguassu",
      "Porto Murtinho",
      "Nova Alvorada do Sul",
      "Corguinho",
      "Jaraguari",
      "Deodápolis",
      "Inocência",
      "Itaporã",
      "Sete Quedas",
      "Ladário",
      "Nioaque",
      "Anastácio",
      "Paraíso das Águas",
      "Glória de Dourados",
      "Angélica",
      "Bodoquena",
      "Laguna Carapã",
      "Selvíria",
      "Tacuru",
      "Santa Rita do Pardo",
      "Rio Negro",
      "Figueirão",
      "Sonora",
      "Antônio João",
      "Eldorado",
      "Itaquiraí",
      "Caracol",
      "Taquarussu",
      "Coxim",
      "Douradina",
      "Japorã",
      "Juti",
      "Bandeirantes",
      "Mundo Novo",
      "Anaurilândia",
      "Dois Irmãos do Buriti",
      "Aral Moreira",
      "Vicentina",
      "Jateí",
      "Novo Horizonte do Sul",
      "Bataiporã",
      "Selvíria",
      "Rio Verde de Mato Grosso",
      "Rochedo",
      "Alcinópolis",
      "Cachoeira Alta",
      "Cassilândia",
      "Chapadão do Sul",
      "Costa Rica",
      "Coxim",
      "Deodápolis",
      "Douradina",
      "Dourados",
      "Eldorado",
      "Fátima do Sul",
      "Figueirão",
      "Glória de Dourados",
      "Guia Lopes da Laguna",
      "Iguatemi",
      "Inocência",
      "Itaporã",
      "Itaquiraí",
      "Ivinhema",
      "Japorã",
      "Jaraguari",
      "Jardim",
      "Jateí",
      "Juti",
      "Ladário",
      "Laguna Carapã",
      "Maracaju",
      "Miranda",
      "Mundo Novo",
      "Naviraí",
      "Nioaque",
      "Nova Alvorada do Sul",
      "Nova Andradina",
      "Novo Horizonte do Sul",
      "Paranaíba",
      "Paranhos",
      "Pedro Gomes",
      "Ponta Porã",
      "Porto Murtinho",
      "Ribas do Rio Pardo",
      "Rio Brilhante",
      "Rio Negro",
      "Rio Verde de Mato Grosso",
      "Rochedo",
      "Santa Rita do Pardo",
      "São Gabriel do Oeste",
      "Selvíria",
      "Sete Quedas",
      "Sidrolândia",
      "Sonora",
      "Tacuru",
      "Taquarussu",
      "Terenos",
      "Três Lagoas",
      "Vicentina"
    ]