

class MT:
    def __init__(self):
        self.cities = [
      "Cuiabá",
      "Várzea Grande",
      "Rondonópolis",
      "Sinop",
      "Tangará da Serra",
      "Cáceres",
      "Sorriso",
      "Lucas do Rio Verde",
      "Primavera do Leste",
      "Barra do Garças",
      "Alta Floresta",
      "Pontes e Lacerda",
      "Nova Mutum",
      "Campo Verde",
      "Juína",
      "Colniza",
      "Guarantã do Norte",
      "Peixoto de Azevedo",
      "Poconé",
      "Aripuanã",
      "Diamantino",
      "Juara",
      "Barra do Bugres",
      "São Félix do Araguaia",
      "Colíder",
      "Nova Xavantina",
      "Sapezal",
      "Porto Alegre do Norte",
      "Comodoro",
      "Matupá",
      "Querência",
      "Carlinda",
      "Mirassol d'Oeste",
      "Nobres",
      "Vila Rica",
      "Nova Canaã do Norte",
      "Jaciara",
      "Campos de Júlio",
      "Tabaporã",
      "Campinápolis",
      "Nova Olímpia",
      "Santo Antônio do Leverger",
      "Colniza",
      "Cocalinho",
      "Conquista d'Oeste",
      "Ribeirão Cascalheira",
      "Rosário Oeste",
      "Nova Bandeirantes",
      "Arenápolis",
      "Nova Marilândia",
      "Acorizal",
      "Juscimeira",
      "Araputanga",
      "Alto Boa Vista",
      "Nova Brasilândia",
      "Paranatinga",
      "Nortelândia",
      "Poxoréu",
      "Juruena",
      "São José do Povo",
      "Nova Santa Helena",
      "Conrado",
      "Santa Terezinha",
      "Lambari d'Oeste",
      "Porto dos Gaúchos",
      "Rondolândia",
      "Cotriguaçu",
      "Salto do Céu",
      "Torixoréu",
      "Curvelândia",
      "Itiquira",
      "Glória d'Oeste",
      "Novo Horizonte do Norte",
      "São Pedro da Cipa",
      "Tesouro",
      "Nova Nazaré",
      "Canabrava do Norte",
      "Cocalinho",
      "Nova Lacerda",
      "Vale de São Domingos",
      "Figueirópolis d'Oeste",
      "Reserva do Cabaçal",
      "São José do Rio Claro",
      "Torixoréu",
      "Nossa Senhora do Livramento",
      "Santa Carmem",
      "Nova Guarita",
      "Nova Maringá",
      "Nova Ubiratã"
    ]