

class PA:
    def __init__(self):
        self.cities = [
      "Belém",
      "Ananindeua",
      "Santarém",
      "Marabá",
      "Castanhal",
      "Parauapebas",
      "Itaituba",
      "Abaetetuba",
      "Cametá",
      "Bragança",
      "Abidos",
      "Moju",
      "Tucuruí",
      "Capanema",
      "Barcarena",
      "Altamira",
      "Paragominas",
      "Igarapé-Miri",
      "Marituba",
      "São Félix do Xingu",
      "Cametá",
      "Canaã dos Carajás",
      "Breves",
      "Oriximiná",
      "Portel",
      "Tailândia",
      "Cachoeira do Arari",
      "Igarapé-Açu",
      "Capitão Poço",
      "Redenção",
      "Conceição do Araguaia",
      "Breu Branco",
      "Rondon do Pará",
      "Uruará",
      "Salinópolis",
      "Jacundá",
      "São Geraldo do Araguaia",
      "Alenquer",
      "Curuçá",
      "Itupiranga",
      "Mocajuba",
      "Afuá",
      "São Miguel do Guamá",
      "Irituia",
      "Placas",
      "Xinguara",
      "Ipixuna do Pará",
      "Óbidos",
      "Novo Progresso",
      "Tucumã",
      "Anapu",
      "São Domingos do Capim",
      "Pacajá",
      "Melgaço",
      "Novo Repartimento",
      "Almeirim",
      "Monte Alegre",
      "Prainha",
      "Irituia",
      "Marapanim",
      "Muaná",
      "Curralinho",
      "Melgaço",
      "Nova Ipixuna",
      "Pacajá",
      "Ourilândia do Norte",
      "Aurora do Pará",
      "Mojuí dos Campos",
      "Dom Eliseu",
      "Mãe do Rio",
      "Goianésia do Pará",
      "Rurópolis",
      "São João de Pirabas",
      "São João do Araguaia",
      "Senador José Porfírio",
      "Porto de Moz",
      "Garrafão do Norte",
      "Vigia",
      "Santa Isabel do Pará",
      "Medicilândia",
      "Igarapé-Açu",
      "Floresta do Araguaia",
      "Floresta do Bico do Papagaio",
    ]