

class PR:
    def __init__(self):
        self.cities = [
      "Curitiba",
      "Londrina",
      "Maringá",
      "Ponta Grossa",
      "Cascavel",
      "São José dos Pinhais",
      "Foz do Iguaçu",
      "Colombo",
      "Guarapuava",
      "Paranaguá",
      "Araucária",
      "Toledo",
      "Apucarana",
      "Pinhais",
      "Campo Largo",
      "Arapongas",
      "Umuarama",
      "Almirante Tamandaré",
      "Piraquara",
      "Cambé",
      "Campo Mourão",
      "Irati",
      "Cianorte",
      "Telêmaco Borba",
      "Castro",
      "Palmas",
      "Paranavaí",
      "Marechal Cândido Rondon",
      "Dois Vizinhos",
      "Pato Branco",
      "Valinhos",
      "Paranapanema",
      "Rolândia",
      "Jandaia do Sul",
      "Campo Magro",
      "Sarandi",
      "Paranaguá",
      "Loanda",
      "Francisco Beltrão",
      "Ibiporã",
      "Jaguariaíva",
      "Astorga",
      "Mandaguari",
      "São Mateus do Sul",
      "Jaguapitã",
      "Matinhos",
      "Medianeira",
      "Colorado",
      "Wenceslau Braz",
      "Assis Chateaubriand",
      "Inácio Martins",
      "Ivaiporã",
      "Cornélio Procópio",
      "Cândido de Abreu",
      "Paiçandu",
      "Reserva",
      "Prudentópolis",
      "Marialva",
      "Carambeí",
      "Palotina",
      "Sertanópolis",
      "Capanema",
      "Tibagi",
      "Campina Grande do Sul",
      "Nova Aurora",
      "Santa Helena",
      "Rolândia",
      "Mandirituba",
      "Rancho Alegre",
      "Santa Terezinha de Itaipu",
      "Bandeirantes",
      "Realeza",
      "Imbituva",
      "Pato Bragado",
      "Joaquim Távora",
      "Pérola",
      "Goioerê",
      "Maringá",
      "Engenheiro Beltrão",
      "Doutor Camargo",
      "Quatro Barras",
      "Fazenda Rio Grande",
      "São Jorge do Ivaí",
      "Mamborê",
      "Pinhão",
      "Altônia",
      "Moreira Sales",
      "Clevelândia",
      "Assaí",
      "Assis Chateaubriand",
      "Bela Vista do Paraíso",
      "Bituruna"
    ]