

class RN:
    def __init__(self):
        self.cities = [
      "Natal",
      "Mossoró",
      "Parnamirim",
      "São Gonçalo do Amarante",
      "Ceará-Mirim",
      "Caicó",
      "Macaíba",
      "Açu",
      "Currais Novos",
      "Santa Cruz",
      "Apodi",
      "Nova Cruz",
      "João Câmara",
      "Canguaretama",
      "Pau dos Ferros",
      "Macau",
      "Areia Branca",
      "Extremoz",
      "Baraúna",
      "São José de Mipibu",
      "Touros",
      "Parelhas",
      "São Miguel",
      "Ipanguaçu",
      "Nísia Floresta",
      "Jucurutu",
      "Lajes",
      "Caiçara do Norte",
      "Ipueira",
      "Carnaúba dos Dantas",
      "Pendências",
      "Jardim do Seridó",
      "Alto do Rodrigues",
      "Lagoa Nova",
      "Serra Negra do Norte",
      "Tangará",
      "Messias Targino",
      "Rodolfo Fernandes",
      "Rafael Fernandes",
      "Carnaubais",
      "Janduís",
      "Tibau",
      "Frutuoso Gomes",
      "Vera Cruz",
      "São Vicente",
      "Lagoa de Velhos",
      "Pedro Velho",
      "São Bento do Norte",
      "Grossos",
      "Lucrécia",
      "Paraná",
      "Viçosa",
      "São Francisco do Oeste",
      "Boa Saúde",
      "Taipu",
      "Riachuelo",
      "Várzea",
      "Senador Eloi de Souza",
      "São Tomé",
      "Almino Afonso",
      "Montanhas",
      "Governador Dix-Sept Rosado",
      "São Rafael",
      "São Pedro",
      "Água Nova",
      "Florânia",
      "Cerro Corá",
      "Jandaíra",
      "Umarizal",
      "São Miguel do Gostoso",
      "Riacho de Santana",
      "Tibau do Sul",
      "Cruzeta",
      "Pedra Preta",
      "Santana do Seridó",
      "Tenente Ananias",
      "Caiçara do Rio do Vento",
      "Galinhos",
      "Marcelino Vieira",
      "Taboleiro Grande",
      "Timbaúba dos Batistas",
      "Campo Redondo",
      "Lajes Pintadas",
      "Japi",
      "São João do Sabugi",
      "Cerro Corá",
      "Passagem",
      "Sítio Novo"
    ]