

class SE:
    def __init__(self):
        self.cities = [
      "Aracaju",
      "Nossa Senhora do Socorro",
      "Lagarto",
      "Itabaiana",
      "São Cristóvão",
      "Estância",
      "Nossa Senhora da Glória",
      "Itabaianinha",
      "Simão Dias",
      "Capela",
      "Nossa Senhora das Dores",
      "Propriá",
      "Barra dos Coqueiros",
      "Poço Redondo",
      "Canindé de São Francisco",
      "Nossa Senhora do Socorro",
      "Laranjeiras",
      "Porto da Folha",
      "Tobias Barreto",
      "Itaporanga d'Ajuda",
      "Umbaúba",
      "Ribeirópolis",
      "Itaporanga d'Ajuda",
      "Neópolis",
      "Carmópolis",
      "Tomar do Geru",
      "Pirambu",
      "Maruim",
      "Rosário do Catete",
      "São Domingos",
      "Arauá",
      "Japaratuba",
      "Salgado",
      "Malhador",
      "Monte Alegre de Sergipe",
      "Carira",
      "Campo do Brito",
      "Siriri",
      "Pedrinhas",
      "Moita Bonita",
      "Ilha das Flores",
      "Macambira",
      "Brejo Grande",
      "Santa Luzia do Itanhy",
      "Cedro de São João",
      "Cristinápolis",
      "Santo Amaro das Brotas",
      "Pinhão",
      "Feira Nova",
      "Areia Branca",
      "Malhada dos Bois",
      "Divina Pastora",
      "General Maynard",
      "Nossa Senhora de Lourdes",
      "Gararu",
      "Gracho Cardoso",
      "Itabi",
      "Santa Rosa de Lima",
      "São Miguel do Aleixo",
      "Cumbe",
      "Pedra Mole",
      "Telha",
      "Amparo de São Francisco",
      "Monte Alegre de Sergipe",
      "Ilha das Flores",
      "Santa Rosa de Lima",
      "São Francisco",
      "São José",
      "Pedra Mole",
      "Itaporanga d'Ajuda",
      "Siriri",
      "Neópolis",
      "Riachuelo",
      "Pirambu",
      "Cedro de São João",
      "Santa Rosa de Lima",
      "General Maynard",
      "Nossa Senhora de Lourdes",
      "Gararu",
      "Gracho Cardoso",
      "Itabi",
      "Santa Rosa de Lima",
      "São Miguel do Aleixo",
      "Cumbe",
      "Pedra Mole",
      "Telha",
      "Amparo de São Francisco",
      "Monte Alegre de Sergipe",
      "Ilha das Flores",
      "Santa Rosa de Lima",
      "São Francisco",
      "São José"
    ]