

class SP:
  def __init__(self):
    self.cities = [
      "São Paulo",
      "Guarulhos",
      "Campinas",
      "São Bernardo do Campo",
      "Santo André",
      "São José dos Campos",
      "Osasco",
      "Ribeirão Preto",
      "Sorocaba",
      "Mauá",
      "Santos",
      "Diadema",
      "Jundiaí",
      "Piracicaba",
      "Carapicuíba",
      "Bauru",
      "Itaquaquecetuba",
      "São Vicente",
      "Franca",
      "Mogi das Cruzes",
      "Suzano",
      "São José do Rio Preto",
      "Praia Grande",
      "Taboão da Serra",
      "Americana",
      "Barueri",
      "Embu das Artes",
      "Maringá",
      "São Caetano do Sul",
      "Jacareí",
      "Sumaré",
      "Presidente Prudente",
      "Guarujá",
      "Taubaté",
      "Araraquara",
      "Itapevi",
      "Rio Claro",
      "Indaiatuba",
      "Pirassununga",
      "Limeira",
      "Assis",
      "Ourinhos",
      "Catanduva",
      "Hortolândia",
      "Barretos",
      "Tatuí",
      "Birigui",
      "Valinhos",
      "Bragança Paulista",
      "Poá",
      "Itu",
      "Pindamonhangaba",
      "Franco da Rocha",
      "Jaú",
      "Lins",
      "Jandira",
      "Botucatu",
      "Sertãozinho",
      "Itapetininga",
      "Votorantim",
      "Taubaté",
      "Lorena",
      "Várzea Paulista",
      "Santa Bárbara d'Oeste",
      "Francisco Morato",
      "Andradina",
      "Jaguariúna",
      "Registro",
      "Penápolis",
      "Itapeva",
      "Mococa",
      "Ituverava",
      "Mairiporã",
      "Cubatão",
      "Mogi Guaçu",
      "Amparo",
      "Mogi Mirim",
      "Cotia",
      "Ferraz de Vasconcelos",
      "Salto",
      "Itatiba",
      "Itanhaém",
      "Cruzeiro",
      "Atibaia",
      "Vinhedo",
      "Santa Cruz do Rio Pardo",
      "São Sebastião",
      "São João da Boa Vista",
      "Marília",
      "Itapeva",
      "Leme"
    ]
  