name: Python Tests

on: 
  workflow_dispatch:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:
  ci:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install requirements.txt
      - name: Run tests
        run: |
          python pytest
