name: Python Tests

on: 
  workflow_dispatch:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:
  ci:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          cd pyFBIG
          python3 -m pip install -r requirements.txt
      - name: Run tests
        run: |
          python3 -m pip install pytest
          pytest tests --cov
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${{secrets.CODECOV_TOKEN}}
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
