name: Python Tests

on: 
  workflow_dispatch:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:
  ci:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          cd pyFBIG
          python3 -m pip install -r requirements.txt
      - name: Run tests
        run: |
          python3 -m pip install pytest
          pytest tests
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
                    

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.2.3
        with:
          github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
      - name: coveralls
        run: |
          pip install coveralls
          coverage run --source=mypkg -m pytest tests/
